### ISSUE TITLE
Possible error in tree section

### ISSUE THREAD

**Issue by richardxu100** [yangshun/tech-interview-handbook#105]
Thanks for this really helpful guide! In your tree section, it says that "When you are asked to traverse a tree by level, use depth first search." In this case, should it be Breadth First Search? I remember doing a Level-Order traversal problem on LeetCode, and to solve it I used BFS with a queue. I think I may be misreading your statement too.

**Comment by louietyj** [comment]
Good catch. The sentence should say "breadth first search" instead. Thanks!
