### ISSUE TITLE
Checklist in place of Bullet Points

### ISSUE THREAD

**Issue by nishitmehta1** [yangshun/tech-interview-handbook#124]
I think using a checklist to display all the weekly problems would be more helpful. The user can mark the problems which he/she already knows.

**Comment by yangshun** [comment]
I don't have the bandwidth to build a progress checklist feature into the website although it's possible to add it. Would you like to try? 😄 

Anyhow, I think users can copy and paste the list to GitHub gists where checkboxes have been implemented.

**Comment by nishitmehta1** [comment]
I think just a frontend checklist would also suffice. If the tab is closed, the data is lost. May sound stupid, but most of them just keep the tab open.

**Comment by yangshun** [comment]
Would require more work than just editing the markdown. I can render the checklist by using the markdown syntax but it won't be interactive.

**Comment by bbbooo313** [comment]
[baoshijienews.com](baoshijienews.com)  老哥换个友链吗？
联系QQ：1297532431

**Comment by yangshun** [comment]
This is better as a LeetCode list. I've created it here - https://leetcode.com/list/xi4ci4ig/
