### ISSUE TITLE
Convert to Superbook

### ISSUE THREAD

**Issue by marvindanig** [yangshun/tech-interview-handbook#132]
Really great resource, thanks for sharing! 

A few of us like to read and remember better with codex style Superbook [1] format. I can convert and publish it for you using a script in a weekend if you want.  

[1] https://bubblin.io/docs/format

**Comment by yangshun** [comment]
Thanks for the thought @marvindanig! However, like you, I'm also a documentation/e-book framework maintainer and this repo's website is built using the [Docusaurus](https://github.com/facebook/docusaurus) framework I maintain with one of the goals being to dogfood my framework. The concept of superbook is cool and I might want to incorporate that into Docusaurus in future.

You're welcome to make a fork of the repo and make the contents superbook-compatible.
