### ISSUE TITLE
[Doubt] Duplicate questions?

### ISSUE THREAD

**Issue by abhijeet1403** [yangshun/tech-interview-handbook#190]
In, URL: https://yangshun.github.io/tech-interview-handbook/algorithms/sorting-searching 
File: tech-interview-handbook/contents/algorithms/sorting-searching.md 

- Sort a list of numbers in which each number is at a distance K from its actual position.
- Sort a list where each element is no more than k positions away from its sorted position.

Are they the same questions?

**Comment by abhijeet1403** [comment]
I get it one is array and one is list. But it actually has the same solution (Using a heap)

**Comment by yangshun** [comment]
Yeah they're similar. Do you want to make a PR?
