### ISSUE TITLE
Alternative to Lago?

### ISSUE THREAD

**Issue by shkmhd** [yangshun/tech-interview-handbook#192]
Suggestion to replace the link to Lago (under Interview Process -> Coding round -> Study and practise) with [TheAlgorithms](https://github.com/TheAlgorithms)  as it contain data structures and algorithms implemented in many more languages (Java, Javascript, Python, C, C++ etc) compared to Lago which focuses only on js.
I can go ahead with a pull request for this if thats okay.

**Comment by yangshun** [comment]
Sure go ahead
