### ISSUE TITLE
Resume case study template

### ISSUE THREAD

**Issue by renjieQ** [yangshun/tech-interview-handbook#224]
Hi Yangshun,
I'd like to download template file in this [https://techinterviewhandbook.org/resume-case-study/](https://techinterviewhandbook.org/resume-case-study/). Could you please help?
![image](https://user-images.githubusercontent.com/53574350/132938012-0c457108-db22-443e-aa95-5ea50f66c3cb.png)

**Comment by yangshun** [comment]
@teikjun would you be kind enough to assist?

**Comment by teikjun** [comment]
Hi @renjieQ, here's a Google Doc template of the resume: 
https://docs.google.com/document/d/1RmwywpUbd6sRzszfH5OkdLr3_v40cyZrQQcxN4X--4c/edit?usp=sharing

To get started, you can either make a copy of it on Google Docs or download it in your desired format:

<img width=200 src="https://user-images.githubusercontent.com/46853051/132981402-2ac9eebc-c6b9-4749-aedc-4a7a93e98574.png" />

Hope this helps! 😄

**Comment by renjieQ** [comment]
Thanks for sharing @teikjun
