### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by WeeHong** [yangshun/tech-interview-handbook#228]
Hello,

I found a broken link [here](https://techinterviewhandbook.org/coding-signals/). 

The [Facebook's Onsite Interview Guide](https://scontent.xx.fbcdn.net/v/t39.2365-6/75448664_529293754518370_5563533277542744064_n.pdf?_nc_cat=108&ccb=1-5&_nc_sid=ad8a9d&_nc_ohc=wLjmSQfO3zQAX_fyaQ7&_nc_ht=scontent.xx&_nc_rmd=260&oh=577831ef9fb665716a3651b82f7041bc&oe=613A5FE8) is not working. 

![B6479585-2102-451D-A0A8-84B32FB2B8C4](https://user-images.githubusercontent.com/6753022/134046400-388e9170-4d47-43a3-a92f-c12ae585872d.png)

**Comment by yangshun** [comment]
Thanks, I shouldn't have used a CDN link which expires after a while. Have updated it in a7aabc8
