### ISSUE TITLE
Fixing Link on website

### ISSUE THREAD

**Issue by SidBthegr8** [yangshun/tech-interview-handbook#234]
On the tech interview handbook website, under the algorithms>Dynamic Programming>Recommended Leetcode questions, the 0/1 Knapsack Problem does not link to a page. Request to assign this issue to me so I can fix it.

**Comment by yangshun** [comment]
Don't need an issue, you can just fix it.

**Comment by arpitghura** [comment]
if this issue resolved then please close this issue
