### ISSUE TITLE
Adding Arcesium(DE Shaw & Co.) to Interview Formats

### ISSUE THREAD

**Issue by MohammedAdain** [yangshun/tech-interview-handbook#235]
Would it be fine if I add Arcesium(DE Shaw & Co.) Interview Formats to [https://techinterviewhandbook.org/interview-formats/](url)? Shall I raise a PR for it?

**Comment by yangshun** [comment]
Thanks for asking! Most of the readers are global and we need to balance the signal to noise ratio on the page, so we'll prioritize larger companies (ideally over 5000 employees).

**Comment by MohammedAdain** [comment]
How about Oracle?

**Comment by MohammedAdain** [comment]
Also can you please review [https://github.com/yangshun/tech-interview-handbook/pull/236](url)

**Comment by yangshun** [comment]
Oracle is fine

**Comment by MohammedAdain** [comment]
Thanks
