### ISSUE TITLE
Kadane's algorithm implementation

### ISSUE THREAD

**Issue by thisabhijeet** [yangshun/tech-interview-handbook#238]
Can I contribute a .cpp file explaining kadane's algorithm implementation and required comments for the maximum contiguous subarray sum problem. I saw the maximum contiguous subarray sum problem on the site . So people can see it's solution on the repo.

**Comment by yangshun** [comment]
Nope, Kadane algorithm is rare and there's not much value in adding that when there are implementations online easily searchable.

**Comment by thisabhijeet** [comment]
okay!
