### ISSUE TITLE
RSS Feed not working

### ISSUE THREAD

**Issue by medic-code** [yangshun/tech-interview-handbook#241]
When accessing via the browser you get a 

`Page Not Found`
`We could not find what you were looking for.`

Looks like a status 404 error. 

Has RSS feeds been phased out on the website ?

https://techinterviewhandbook.org/blog/rss.xml
https://techinterviewhandbook.org/blog/atom.xml

Tried a couple of different RSS feed readers, as well as without success. Just thought I'd bring this to your attention. Would love to see this fixed!

**Comment by jazcarate** [comment]
I was debugging this error, and found it is a problem with `docusaurus` itself. I just opened a PR on their repo: https://github.com/facebook/docusaurus/pull/5846

**Comment by yangshun** [comment]
Seems fine now thanks for reporting!
