### ISSUE TITLE
[Broken Link] Under Reference section of "Algorithm -> Introduction Page"

### ISSUE THREAD

**Issue by harishraja1217** [yangshun/tech-interview-handbook#251]
Webpage : https://techinterviewhandbook.org/algorithms/introduction/#references

Under this section, the 3rd URL is broken : https://quip.com/q41AA3OmoZbC
Moreover, the URL redirects to https://quip.com/cVcAAAJJ9qq for me.

**Screenshot :**
![image](https://user-images.githubusercontent.com/49875660/143600034-21e47694-b221-4dca-bd25-1d2b556e282a.png)

This is my first issue in github, BTW.

**Comment by yangshun** [comment]
Thanks, I'll remove it
