### ISSUE TITLE
Add a "What is being measured" section into the "Preparation" page

### ISSUE THREAD

**Issue by yangshun** [yangshun/tech-interview-handbook#26]
Elynn Lee has written great content about it [here](https://www.quora.com/Why-do-I-do-poorly-in-interviews-although-I-am-strong-technically/answer/Elynn-Lee). Unfortunately it is not for reproduction and some rephrasing + more research will have to be done.

**Comment by dhruvmalik007** [comment]
Well  the section "What is being measured"   Must be replaced with Evaluation Parameters , that is more trendy #add Evaluation parameters

**Comment by darrenlittlejohn** [comment]
I can probably help with this. I'm a technical writer and am just entering into the job market so this guide something I'm passionate about.

**Comment by yangshun** [comment]
Hey @darrenlittlejohn thanks but I'm halfway through it. Appreciate the thought!

**Comment by yangshun** [comment]
CLosing this as we have a [coding signals page](https://yangshun.github.io/tech-interview-handbook/coding-signals) now!
