### ISSUE TITLE
Add links to Design Gurus' courses?

### ISSUE THREAD

**Issue by j42huynh** [yangshun/tech-interview-handbook#264]
Instead of paying a subscription for "Grokking the System Design Interview by Educative", people can also pay for lifetime access for the same course from [Design Gurus](https://designgurus.org/courses) (along with others). This might be an option people want to consider when paying for a course.

**Comment by yangshun** [comment]
Oh cool, I never knew about this separate website. I'll look into it

**Comment by yangshun** [comment]
Done!

**Comment by Mark-Hezekiah** [comment]
That's really good. Thanks for the info.
