### ISSUE TITLE
Typo on Queue page

### ISSUE THREAD

**Issue by Crabstove** [yangshun/tech-interview-handbook#277]
[In essential questions of Queue page](https://www.techinterviewhandbook.org/algorithms/queue/#essential-questions) it says Implement Stack using Queues, but it links to Implement Queue using Stacks problem. I got a little confused by it while studying, since in the next section of Recommended Practice Questions you have the correct link and label for Implement Queue using Stacks, but the previous problem with a different name links to the same problem. 

Here are the correct links for [Implement Stack using Queues](https://leetcode.com/problems/implement-stack-using-queues/) and [Implement Queue using Stacks](https://leetcode.com/problems/implement-queue-using-stacks/) for quick reference.

**Comment by yangshun** [comment]
Thanks for reporting it. Fixed via f1b4cdc
