### ISSUE TITLE
Edit this page redirecting to 404

### ISSUE THREAD

**Issue by Sinha1994** [yangshun/tech-interview-handbook#290]
Go to [https://www.frontendinterviewhandbook.com/coding/build-front-end-user-interfaces](https://www.frontendinterviewhandbook.com/coding/build-front-end-user-interfaces) scroll to the bottom, when clicking on [Edit this page](https://github.com/yangshun/front-end-interview-handbook/edit/master/contents/build-front-end-user-interfaces.md) it's redirecting to 404

<img width="772" alt="image" src="https://user-images.githubusercontent.com/28135546/181906862-16ede92d-cb5a-4a7a-b448-5065f389a36f.png">

<img width="880" alt="image" src="https://user-images.githubusercontent.com/28135546/181906872-45689354-b26b-4f2f-8dec-134b5dd0e71c.png">

**Comment by yangshun** [comment]
Wrong repo?

**Comment by yangshun** [comment]
Will fix in the other repo

**Comment by yangshun** [comment]
Fixed by https://github.com/yangshun/front-end-interview-handbook/pull/353, thanks to @PrinceSumberia
