### ISSUE TITLE
Not finished sentence

### ISSUE THREAD

**Issue by iechodropz** [yangshun/tech-interview-handbook#300]
In Writing your software engineer resume, under Test readability with industry-standard ATS. I see "Test the readability and formatting of your resume using." and it doesn't finish telling me using what.

**Comment by arnabpal2022** [comment]
Can you provide the exact address of the resume? Can't Locate..

**Comment by developerdenesh** [comment]
Seems like the line in question is: https://github.com/yangshun/tech-interview-handbook/blob/ce8f3c6346fafcf3db7b2d5fefb87f550236f8eb/apps/website/contents/resume.md#2-test-readability-with-industry-standard-ats

**Comment by bwitt** [comment]
this one, right?  github makes it so hard to link to lines in md files!
https://github.com/yangshun/tech-interview-handbook/blob/ce8f3c6346fafcf3db7b2d5fefb87f550236f8eb/apps/website/contents/resume.md?plain=1#L336

**Comment by arnabpal2022** [comment]
#558 check this please.
