### ISSUE TITLE
Typo in HTML Interview Questions

### ISSUE THREAD

**Issue by Klestofer** [yangshun/tech-interview-handbook#32]
[Here](https://github.com/yangshun/tech-interview-handbook/blob/master/front-end/interview-questions.md#why-is-it-generally-a-good-idea-to-position-css-links-between-headhead-and-js-scripts-just-before-body-do-you-know-any-exceptions) it probably should be `Placing <script>s just before </body>`.

**Comment by yangshun** [comment]
Thanks for catching! Would you like to make a PR to fix it? 

Btw there's [Hacktoberfest](https://hacktoberfest.digitalocean.com/) going on now and submitting PRs to this repo is a great way to earn the t-shirt 😎

**Comment by Klestofer** [comment]
No.

**Comment by yangshun** [comment]
Fixed by 621472e

**Comment by Klestofer** [comment]
One more typo: Placing <script**s**>s
