### ISSUE TITLE
mergeSort method doesn't handle null case

### ISSUE THREAD

**Issue by viswanadha-kondoju-ck** [yangshun/tech-interview-handbook#40]
mergeSort method doesn't handle null case, it should handle the case where arr is null

**Comment by yangshun** [comment]
The sorting methods expect an input array. The focus is on the algorithm and not the handling of edge cases.  If all algorithms had to handle invalid input case then it would be too much of a trouble to implement them.

For example, if you were to try passing in `None` to the `sorted()` method in Python, you get the following.

```py
>>> sorted(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not iterable
```

We can (and should) assume valid input for algorithm functions.

**Comment by viswanadha-kondoju-ck** [comment]
thanks for answering my question, i hope you don't mind me asking such questions

**Comment by yangshun** [comment]
Not at all 😄
