### ISSUE TITLE
Gender inclusive?

### ISSUE THREAD

**Issue by kosmotaur** [yangshun/tech-interview-handbook#44]
You speak about shirt and tie. Now of course there's nothing stopping a woman from wearing that, but wouldn't you agree that this makes it sound like you're only addressing a male audience?

**Comment by yangshun** [comment]
That's a very good point and definitely not my intention to only address a male audience. My bad. Do you have suggestions on the wording?

**Comment by kosmotaur** [comment]
How about:

> Dress comfortably. Usually you do not need to wear smart clothes, casual should be fine.

**Comment by yangshun** [comment]
Thanks! Have incorporated your suggestion. Fixed by #91f799a

**Comment by kosmotaur** [comment]
Great, thanks!
