### ISSUE TITLE
Resources for folks on the other side of the table?

### ISSUE THREAD

**Issue by seanhagen** [yangshun/tech-interview-handbook#55]
This is an awesome resource for people looking to polish their skills for when they go into interviews.

Are there any plans to add some resources for the interviewers? IE, the brand new tech lead who needs to hire a junior but has no idea what kinds of questions to ask, or the manager who doesn't know a ton but needs to find just the right dev for their open position.

**Comment by yangshun** [comment]
Oh yes that's in the works. To be fair, there's more demand for resources for interviewees rather than interviewers, so that'll be the focus for now. But it's something we're definitely keeping in mind 😎

**Comment by seanhagen** [comment]
Awesome!

I totally understand that there are more folks looking for help being interviewees, rather than interviewers, but knowing it's on the roadmap is great :smile:

**Comment by bbbooo313** [comment]
[www.dafacaipw.com](www.dafacaipw.com)  老哥换个友链吗？
联系QQ：1297532431

**Comment by yangshun** [comment]
Some brief resources here - https://techinterviewhandbook.org/interviewer-cheatsheet/
