### ISSUE TITLE
Typo on Behavioral Interview page

### ISSUE THREAD

**Issue by sid-707** [yangshun/tech-interview-handbook#569]
The [**Try out mock behavioral interviews** section](https://github.com/yangshun/tech-interview-handbook/blob/main/apps/website/contents/behavioral-interview.md#4-try-out-mock-behavioral-interviews) says `Apply` instead of `Apple`.

**Comment by mahehsblogs** [comment]
Hi, I am new to open source and want to contribute to "some good first" issues. Could you let me know if this issue has been resolved??

**Comment by yangshun** [comment]
@mahehsblogs Yes it has been resolved in #570. Perhaps you could read through the website and look for typos or other areas you can improve the content, then make a Pull Request. If you'd like to add features please create an issue to discuss and align first.

**Comment by yangshun** [comment]
Perhaps you could work on https://github.com/yangshun/tech-interview-handbook/issues/545

**Comment by mahehsblogs** [comment]
Ok, @yangshun Thanks for guiding me.

**Comment by mahehsblogs** [comment]
Hi, @yangshun I made changes and create a pull request could you please check if is it the correct PR or not?[#573](https://github.com/yangshun/tech-interview-handbook/pull/573)
