### ISSUE TITLE
Work From Home

### ISSUE THREAD

**Issue by Michealjordab55** [yangshun/tech-interview-handbook#646]
Hello, I am looking for talented and professional freelancers, enter the necessary options:

    ~Data entry jobs

    ~Translation

    ~writing Jobs

    ~Typing jobs

    Payment: $1,500

    If you are interested kindly inbox me on my DM. Thank you
@everyone

**Comment by Precious-Macaulay** [comment]
bro am interested

**Comment by amarpals203** [comment]
i am interested

**Comment by ClarisseNicole8** [comment]
I am interested.
