### ISSUE TITLE
The site seems to be down.

### ISSUE THREAD

**Issue by Imran31** [yangshun/tech-interview-handbook#657]
https://www.techinterviewhandbook.org/grind75

<img width="873" alt="Screenshot 2024-09-17 at 2 55 10 PM" src="https://github.com/user-attachments/assets/c66b873d-8e16-45d9-8d6c-6e6d63fc3c07">

**Comment by yangshun** [comment]
Hi yes I'm in the process of moving the DNS to Cloudflare, so there will be some downtime.

**Comment by yangshun** [comment]
Should be up now. Please reopen if it's not!
