### ISSUE TITLE
Grind 75 link is down

### ISSUE THREAD

**Issue by sbetageri** [yangshun/tech-interview-handbook#658]
<img width="1800" alt="Screenshot 2024-09-18 at 8 08 16 PM" src="https://github.com/user-attachments/assets/84fb7953-f914-4d50-9593-4b9894936ad2">

**Comment by patleeman** [comment]
Looks related to this PR? https://github.com/yangshun/tech-interview-handbook/commit/02826f04efe5016fc0b0b06b0863588a2df29049

**Comment by yangshun** [comment]
Sorry there was a bad deployment. Fixed
