### ISSUE TITLE
Bug: Contribute your success stories/testimonials not working

### ISSUE THREAD

**Issue by yehiarasheed** [yangshun/tech-interview-handbook#665]
## Bug Description: 
As could be seen in the pinned issue #255 and the website itself under the **Success stories** Section on the main page, the link to [open a pull request](https://github.com/yangshun/tech-interview-handbook/edit/master/website/src/data/successStories.js) is not working since the file named successStories.js has been renamed to `apps/website/src/data/successStories.js` from its initial name `master/website/src/data/successStories.js`. This issue seems to have been going on for a long time, can't imagine how many success stories have been left out.

## Screenshots
![image](https://github.com/user-attachments/assets/eba2570f-3785-4e0a-a86e-d9d87de50e7d)
![image](https://github.com/user-attachments/assets/c20baa1a-83e6-46f6-b783-cdd9de20cc13)

### The cause of the problem 
![image](https://github.com/user-attachments/assets/1dd4ba2e-afdf-461a-b69f-b9e09c83c247)
![image](https://github.com/user-attachments/assets/2cca1433-a13b-4423-9976-df57a4a97202)

I will follow up on this with a PR fixing it, I suggest that @yangshun edits the issue after I fix it with the correct working link to proceed with publishing the success stories.

**Comment by yangshun** [comment]
Thanks, looking forward
